---
version: 2.0
params:
  - name: PIPELINE_NUMBER
    value: ""
  - name: PIPELINE_ID
    value: ""
steps:
  PRE_BUILD:
  - checkout:
      name: "checkout"
      inputs:
        scm: "codehub"
        url: "git@codehub.devcloud.ap-southeast-3.huaweicloud.com:92720a0c9cba4d5696a8251876fc255f/policy-as-code-lab.git"
        branch: "main"
        lfs: false
        submodule: false
  BUILD:
  - swr:
      name: "Terraform Validation"
      inputs:
        command: |
          export HW_ACCESS_KEY=${HW_ACCESS_KEY}
          export HW_SECRET_KEY=${HW_SECRET_KEY}
          export AWS_ACCESS_KEY_ID=${HW_ACCESS_KEY}
          export AWS_SECRET_ACCESS_KEY=${HW_SECRET_KEY}
          terraform -chdir=infrastructure init
          terraform -chdir=infrastructure validate
          terraform -chdir=application init
          terraform -chdir=application validate

  - swr:
      name: "Chckov Policy Validation for Infrastructure"
      inputs:
        command: |
          checkov -d infrastructure --download-external-modules true --external-checks-git https://github.com/Huawei-APAC-Professional-Services/terraform-policy.git

  - swr:
      name: "Chckov Policy Validation for application"
      inputs:
        command: |
          checkov -d application --download-external-modules true --external-checks-git https://github.com/Huawei-APAC-Professional-Services/terraform-policy.git

  - swr:
      name: "Terraform Plan - Infra"
      inputs:
        command: |
          terraform -chdir=infrastructure init
          terraform -chdir=infrastructure plan

  - swr:
      name: "Terraform apply - Infra"
      inputs:
        command: |
          terraform -chdir=infrastructure init
          terraform -chdir=infrastructure apply -auto-approve

  - swr:
      name: "Terraform Plan - app"
      inputs:
        command: |
          terraform -chdir=application init
          terraform -chdir=application plan

  - swr:
      name: "Terraform apply - app"
      inputs:
        command: |
          terraform -chdir=application init
          terraform -chdir=application apply -auto-approve